# ===============================
# PostgreSQL Config
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/rahwan
spring.datasource.username=rahwan
spring.datasource.password=rahwan


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Server
# ===============================
server.port=8089
#server.address=0.0.0.0

## ===============================
## Security (Default Admin)
## ===============================
# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation2024RahwanProjectBlueWhale
jwt.expiration=31536000000
# 86400000 ms = 24 hours

# ===============================
# Swagger / OpenAPI
# ===============================
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.csrf.enabled=false
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.e vnabled=true
springdoc.swagger-ui.doc-expansion=none

# ===============================
# Google maps API
# ===============================
google.maps.api.key=AIzaSyBB43hKdQSbk1UKkCapWeawhpp9JbQhCoc
google.maps.api.base-url=https://maps.googleapis.com/maps/api
google.maps.api.timeout=5000
google.maps.api.max-retries=2

# Distance Calculation Settings
distance.calculation.primary-method=GOOGLE_MAPS
distance.calculation.fallback-enabled=true
distance.calculation.cache-enabled=true
distance.calculation.cache-ttl-minutes=60

# Logging
logging.level.com.blueWhale.Rahwan.order.service=DEBUG


# ===============================
# WhatsApp API
# ===============================
whatsapp.api.base-url=https://api.wapilot.net/api/v2
whatsapp.api.token=00UbfqjfCyNUhDiGYzsJF3skAhLJ0XIlR1FjOSnqDd
whatsapp.api.instance-id=instance2928

# ===============================
# App Wallet ID (UUID)
# ===============================
#private static final UUID APP_WALLET_ID = UUID.fromString("PUT-YOUR-APP-UUID-HERE");


# ===============================
# Jackson
# ===============================
spring.jackson.serialization.write-dates-as-timestamps=false

